# Generated by Django 4.1 on 2022-11-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_paymentmethod_supplier_sale_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restockaudit',
            name='inventory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.inventory'),
        ),
    ]
