# Generated by Django 4.1 on 2022-09-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_sale_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='final_total_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_price',
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
