# Generated by Django 4.1 on 2023-01-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_historicalsale_shop_sale_shop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsale',
            old_name='Shop',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='Shop',
            new_name='shop',
        ),
    ]
