# Generated by Django 4.1 on 2022-11-15 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_alter_restockaudit_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restockaudit',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='restockaudit',
            name='price_id',
        ),
        migrations.RemoveField(
            model_name='restockaudit',
            name='sale_price',
        ),
        migrations.AlterField(
            model_name='restockaudit',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.inventory'),
        ),
    ]
