# Generated by Django 4.1 on 2022-09-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_remove_sale_discount_remove_sale_final_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='final_total_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
