# Generated by Django 4.1 on 2022-11-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_remove_restockaudit_cost_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestockAudit',
        ),
    ]
