# Generated by Django 4.1 on 2022-11-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_errorticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorticket',
            name='staff',
        ),
    ]
