# Generated by Django 4.1.1 on 2022-10-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_salesitem_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total_price',
            new_name='total_profit',
        ),
    ]
