# Generated by Django 4.1.1 on 2022-10-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0008_rename_total_price_sale_total_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
