# Generated by Django 4.1 on 2022-11-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0008_remove_errorticket_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorticket',
            name='staus',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Seen', 'Seen')], default='Pending', max_length=50, null=True),
        ),
    ]
