# Generated by Django 4.1 on 2022-11-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0011_errorticket_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorticket',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='errorticket',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
