# Generated by Django 4.1 on 2022-11-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0012_errorticket_date_added_errorticket_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('POS', 'POS')], default='Cash', max_length=50, null=True),
        ),
    ]
