# Generated by Django 4.1 on 2022-12-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0014_remove_sale_method_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('POS', 'POS')], default='Cash', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
