# Generated by Django 4.1 on 2022-12-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0015_sale_method_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='mode_of_sales',
        ),
    ]
