# Generated by Django 4.1 on 2022-12-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0016_remove_sale_mode_of_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
