# Generated by Django 4.1 on 2022-12-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0017_delete_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
