# Generated by Django 4.1 on 2022-12-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0020_historicalsale_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='cost_total',
            field=models.FloatField(default=0),
        ),
    ]
