# Generated by Django 4.1 on 2022-12-29 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pos',
            options={'verbose_name_plural': 'pos'},
        ),
        migrations.AlterField(
            model_name='pos',
            name='name',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
