# Generated by Django 4.1 on 2022-11-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_errorticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorTicket',
        ),
    ]
