# Generated by Django 4.1 on 2022-12-30 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_pos_name_alter_pos_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='staff',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
