# Generated by Django 4.1 on 2022-12-30 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_pos_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pos',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
